### ISSUE TITLE
RZR  in off-road environment with rough terrain

### ISSUE THREAD

**Issue by owenliu-rdc** [Tinker-Twins/AutoDRIVE#11]
Hi!  this is a fantastic project!

Here's a description of my issue:
When I download the latest release of AutoDRIVE Simulator (0.3.0) --windows version ,  i found I could not change the map and vehicle,i want a simulate environment  :RZR  in off-road environment with rough terrain ; how can i get it ? could you give an release edition 
of this?

I'd be very grateful. Thanks!!

**Comment by owenliu-rdc** [comment]
I try to build a simulation scene myself,i  use Unity Hub 3.8.0 with unity 2021.3.34f1,then i download the newest AutoDRIVE-Simulator,Unzip source files larger than 100 MB,Launch Unity Hub and select ADD project button. Navigate to the download directory and select the parent folder of the AutoDRIVE repository.  i open the RZR scene, but there are errors:mainly identifier uniqueness violation and can not import normals,which i thought cause the problem: the rzr model  mesh filter show missing(mesh) error,finally the rzr model cannot show ,is there any mistake i make?which unity version should i use ? or which scene is well for rzr terrain simulation?

**Comment by owenliu-rdc** [comment]
it seems the reason is the RZR.prefab has errors ,   meshes missing

**Comment by Tinker-Twins** [comment]
Hi @owenliu-rdc,

The issue you are referring to occurs if the `.meta` files don't point to the correct asset, as described in [Unity's official documentation](https://docs.unity3d.com/Manual/AssetMetadata.html):

> If an asset loses its meta file (for example, if you move or rename the asset outside of Unity, but don’t move or rename the corresponding .meta file), any reference to that asset is broken in your project. In this situation, Unity notices that the asset does not have a corresponding meta file, generates a new one for the moved/renamed asset as if it is a brand new asset, and deletes the old “orphaned” .meta file.

The challenge is that we cannot upload the raw assets to the repository due to GitHub's 100 MB restriction per file. Consequently, we have added zipped files, which can be un-zipped **before** launching the Unity project for the first time. We have verified that this works most of the times, but may fail in certain cases, leading to the same issue that you are facing.

For now, we have uploaded the entire source project on Google Drive, which can be downloaded, un-zipped, and imported into Unity Hub (tested with Unity 2021.3.34f1). Here's a [link](https://drive.google.com/file/d/13VyiwF7xcd4qI74V5VXGlCCfz3Kp5Yeg/view?usp=sharing) to it. However, please note that we may not maintain the Google Drive version as frequently as the GitHub version of the simulator.

Hope this helps!
