### ISSUE TITLE
The vehicle rotating on same spot Nigel

### ISSUE THREAD

**Issue by STEEVEPP** [Tinker-Twins/AutoDRIVE#13]
When i am running the main run file like 
bash run_nigel.sh
python3 example_nigel.py

when i connected to autonomous the vehicle is rotating on same spot
How i can fix is iam missing anything 
please help me

**Comment by Tinker-Twins** [comment]
Hi @STEEVEPP,

That is the intended/expected behavior.

Essentially, [`example_nigel.py`](https://github.com/Tinker-Twins/AutoDRIVE/blob/AutoDRIVE-Devkit/ADSS%20Toolkit/autodrive_py/example_nigel.py#L76-L77) is meant to be a starting point prototyping template. The script initializes the necessary objects and assigns values of 1 to the `throttle_command` and `steering_command` for the vehicle. This makes the vehicle steer to the extreme left and drive forward with full throttle possible. Please refer to the comments to understand the code structure and workflow better. Once it is clear, you can implement the perception, planning and control logic yourself as per your problem statement and have fun experimenting with the different parameters associated and see their effect on vehicle performance.

Hope this helps and all the best!
